# This GitHub action deploys to production
name: CD - Cloud Run
on:
#  push:
#    branches:
#      - master

jobs:
  build_and_deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
      - name: Send Credentials to Google
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set compute/region us-east1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker Image
        run: docker push $IMAGE_NAME
