# This GitHub action deploys to production
name: CD - Cloud Run
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
      - name: Send Credentials to Google
        uses: google-github-actions/setup-gcloud@master
        with:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Instance
        run: |
          gcloud compute ssh ${{ secrets.GCP_COMPUTE_INSTANCE_NAME }} --zone us-central1-a
          cd ~/poly-doc-backend
          git checkout master
          git pull origin master
          docker-compose down
          docker-compose up --build --remove-orphan -d
          exit
